version: '3.8'
services:
  auth-db:
    image: postgres:15
    restart: always
    container_name: auth-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: abacus_auth
    ports:
      - '5432:5432'
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data: